# This is a basic workflow to help you get started with Actions

name: name_of_workflow
on: workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps:
        - name: Print Output
          run: echo " Created Own"
    
  
